const Cipher = require("../dist/index.cjs").default;

const { encrypt, decrypt } = new Cipher({
  encryption_key: "uEKBcN7kMKayW6SF8d0BtaJq60Musbp0",
  initialization_vector: "hA7wB3e4v87ihj6R",
});

const value = decrypt({
  responseCode: "100",
  data: [
    {
      security_code: "o20Ux3v771ml3v+oeN7n0Q==",
      board: "dMRMiwJD5O6TpCSH860VQA==",
      price: "UmD8xBeWj3BfVpp93PsT+w==",
      lowest_price: "hbjDSgwTHiLvYU7wKftgpQ==",
      location_code: "hpd+GzN3O+XRc5nU+c/41w==",
      highest_price: "9aS7p0WUZgB0M+xUp96r0w==",
      created: "WBjHzSANY8gFnZ4US+A/f34DFobHXWwVIp95w+c9s7w=",
      transaction_fee_configurations: [
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "AVeouTen7Ey9zknY3SIwuw==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "By2IYWN2DMFKGsUcq0fYow==",
          fee_description: null,
          fee_value: "7+OMVwfq0o4tgE5uCCepfg==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "By2IYWN2DMFKGsUcq0fYow==",
          fee_description: null,
          fee_value: "7+OMVwfq0o4tgE5uCCepfg==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "AVeouTen7Ey9zknY3SIwuw==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
      ],
    },
    {
      security_code: "2r0rfPEHxcxOp8z6q32btw==",
      board: "dMRMiwJD5O6TpCSH860VQA==",
      price: "g1Oi4EhaGnYZZCRqYTYxeQ==",
      lowest_price: "puGJvNMYyybl9j3/KlFcPQ==",
      location_code: "hpd+GzN3O+XRc5nU+c/41w==",
      highest_price: "kYD9EwjCOdGgYeB2TBrsDQ==",
      created: "9nEsX0M8rIXKcRuhWV/O0vrS+3a/KRPOlAH1xCaNAd4=",
      transaction_fee_configurations: [
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "AVeouTen7Ey9zknY3SIwuw==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "AVeouTen7Ey9zknY3SIwuw==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "By2IYWN2DMFKGsUcq0fYow==",
          fee_description: null,
          fee_value: "7+OMVwfq0o4tgE5uCCepfg==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "By2IYWN2DMFKGsUcq0fYow==",
          fee_description: null,
          fee_value: "7+OMVwfq0o4tgE5uCCepfg==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
      ],
    },
    {
      security_code: "X+np+GeYiijaHW7VvtEILA==",
      board: "UeFth9EF5b5o1zMlVc9Z4w==",
      price: "BWGvXWBHbrkREnrgOfVurg==",
      lowest_price: "BWGvXWBHbrkREnrgOfVurg==",
      location_code: "LXPsSmw2z60ROe+6BJMqxQ==",
      highest_price: "BWGvXWBHbrkREnrgOfVurg==",
      created: "zi282ObOYXg/Bpdagr1naF448f/oNs8Fu65V5I26Y90=",
      transaction_fee_configurations: [
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_value: "AVeouTen7Ey9zknY3SIwuw==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "AVeouTen7Ey9zknY3SIwuw==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "rWCOwpu2jWPfEn8TyZQsKw==",
          fee_description: null,
          fee_value: "7+OMVwfq0o4tgE5uCCepfg==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "rWCOwpu2jWPfEn8TyZQsKw==",
          fee_description: null,
          fee_value: "7+OMVwfq0o4tgE5uCCepfg==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
      ],
    },
    {
      security_code: "VR7HBQDVOOTMk05kns2+3g==",
      board: "UeFth9EF5b5o1zMlVc9Z4w==",
      price: "eS7nzi3VwKcYzk2DOJT4Tw==",
      lowest_price: "eS7nzi3VwKcYzk2DOJT4Tw==",
      location_code: "w34ElTMf5sQajXINvLi97Q==",
      highest_price: "eS7nzi3VwKcYzk2DOJT4Tw==",
      created: "COuEfOtAALTRrEJIZoehuSvnebONnsIFewbDNFvVL/E=",
      transaction_fee_configurations: [
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "rWCOwpu2jWPfEn8TyZQsKw==",
          fee_description: null,
          fee_value: "7+OMVwfq0o4tgE5uCCepfg==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "rWCOwpu2jWPfEn8TyZQsKw==",
          fee_description: null,
          fee_value: "7+OMVwfq0o4tgE5uCCepfg==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "T2sc5TxLUcJzoZOTfrRrEA==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "DWZCCzRY2dgPj9AbOoiWHA==",
          fee_type: "goZcMufGqYMaTGkgKe135Q==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
      ],
    },
    {
      security_code: "0Od4JQH54mMtTkCUSdIb2g==",
      board: "dMRMiwJD5O6TpCSH860VQA==",
      price: "QI9/HlwFKlDsaSD2l4Kndw==",
      lowest_price: "6oudthHZjSvcgITZM931ug==",
      location_code: "",
      highest_price: "QI9/HlwFKlDsaSD2l4Kndw==",
      created: "0NdBCLNPOgYTztBySZnq5iL2yEz/RPJCtlpdxUogAeQ=",
      transaction_fee_configurations: [
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "YWinTOv4p75O3x0gwTs/5A==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "rWCOwpu2jWPfEn8TyZQsKw==",
          fee_description: null,
          fee_value: "7zwb8FmK8AAlE+LVwdebJA==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "YWinTOv4p75O3x0gwTs/5A==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "igG5/RWqdecrZAyvpZ2MtbDNcEAsloOA9k4WIb+FCn0=",
          fee_description: null,
          fee_value: "mIhXkzXjLpwgjS5mJGDyrA==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "6bg/NG/QhfTMhjbXdNAVyg==",
          fee_description: null,
          fee_value: "TmN904SMldiFtcHgpXve9A==",
          fee_type: "vScdnIitO0dwckA9Kn7gsA==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "6bg/NG/QhfTMhjbXdNAVyg==",
          fee_description: null,
          fee_value: "TmN904SMldiFtcHgpXve9A==",
          fee_type: "vScdnIitO0dwckA9Kn7gsA==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
      ],
    },
    {
      security_code: "T1YcPYvdKI3rIW0oWlw7Jg==",
      board: "dMRMiwJD5O6TpCSH860VQA==",
      price: "WxfIOihIbqAFzR9OHQn/Iw==",
      lowest_price: "meqqv/NNw9nNFZXgSXzizw==",
      location_code: "",
      highest_price: "WxfIOihIbqAFzR9OHQn/Iw==",
      created: "AUtgav5MXHz/HGDM7as0FO1YiygAZM5g8MNcYUVWln0=",
      transaction_fee_configurations: [
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "YWinTOv4p75O3x0gwTs/5A==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "rWCOwpu2jWPfEn8TyZQsKw==",
          fee_description: null,
          fee_value: "7zwb8FmK8AAlE+LVwdebJA==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "YWinTOv4p75O3x0gwTs/5A==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "igG5/RWqdecrZAyvpZ2MtbDNcEAsloOA9k4WIb+FCn0=",
          fee_description: null,
          fee_value: "mIhXkzXjLpwgjS5mJGDyrA==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "6bg/NG/QhfTMhjbXdNAVyg==",
          fee_description: null,
          fee_value: "TmN904SMldiFtcHgpXve9A==",
          fee_type: "vScdnIitO0dwckA9Kn7gsA==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "6bg/NG/QhfTMhjbXdNAVyg==",
          fee_description: null,
          fee_value: "TmN904SMldiFtcHgpXve9A==",
          fee_type: "vScdnIitO0dwckA9Kn7gsA==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
      ],
    },
    {
      security_code: "FMeprgvPK/Fj6iBL9UGeYA==",
      board: "dMRMiwJD5O6TpCSH860VQA==",
      price: "Z9x2TcKKL11Aor4Vf6w5iQ==",
      lowest_price: "P6+T4gggdsSEvScWTMzuGw==",
      location_code: "",
      highest_price: "rt/jFNiNNaRDmCrhW4/xcw==",
      created: "AhY366i3BmNqWd4PcliXqdepaEehH/0iXbIywQbCj0w=",
      transaction_fee_configurations: [
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "6bg/NG/QhfTMhjbXdNAVyg==",
          fee_description: null,
          fee_value: "TmN904SMldiFtcHgpXve9A==",
          fee_type: "vScdnIitO0dwckA9Kn7gsA==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "6bg/NG/QhfTMhjbXdNAVyg==",
          fee_description: null,
          fee_value: "TmN904SMldiFtcHgpXve9A==",
          fee_type: "vScdnIitO0dwckA9Kn7gsA==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "YWinTOv4p75O3x0gwTs/5A==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "rWCOwpu2jWPfEn8TyZQsKw==",
          fee_description: null,
          fee_value: "7zwb8FmK8AAlE+LVwdebJA==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "YWinTOv4p75O3x0gwTs/5A==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "igG5/RWqdecrZAyvpZ2MtbDNcEAsloOA9k4WIb+FCn0=",
          fee_description: null,
          fee_value: "mIhXkzXjLpwgjS5mJGDyrA==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
      ],
    },
    {
      security_code: "d03RT1PtSwSUrGczoxmCbg==",
      board: "dMRMiwJD5O6TpCSH860VQA==",
      price: "2NQ5ZrkjyVNjQ380/ZF9ng==",
      lowest_price: "2NQ5ZrkjyVNjQ380/ZF9ng==",
      location_code: "",
      highest_price: "RiUXmc83tW7jOaQyLkfYHw==",
      created: "neKG6qyyNI/4XyiK8dOUGQy5tEXHa86W2tBQivmRf0k=",
      transaction_fee_configurations: [
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "6bg/NG/QhfTMhjbXdNAVyg==",
          fee_description: null,
          fee_value: "TmN904SMldiFtcHgpXve9A==",
          fee_type: "vScdnIitO0dwckA9Kn7gsA==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "YWinTOv4p75O3x0gwTs/5A==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "rWCOwpu2jWPfEn8TyZQsKw==",
          fee_description: null,
          fee_value: "7zwb8FmK8AAlE+LVwdebJA==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "YWinTOv4p75O3x0gwTs/5A==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "igG5/RWqdecrZAyvpZ2MtbDNcEAsloOA9k4WIb+FCn0=",
          fee_description: null,
          fee_value: "mIhXkzXjLpwgjS5mJGDyrA==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "6bg/NG/QhfTMhjbXdNAVyg==",
          fee_description: null,
          fee_value: "TmN904SMldiFtcHgpXve9A==",
          fee_type: "vScdnIitO0dwckA9Kn7gsA==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
      ],
    },
    {
      security_code: "zidRajBNHWNJ0m2r94zzsQ==",
      board: "dMRMiwJD5O6TpCSH860VQA==",
      price: "AJccqT/3DiHG/u1PvMv6Ng==",
      lowest_price: "bb9Jw2a47QNQ14fAPqwm0Q==",
      location_code: "",
      highest_price: "AJccqT/3DiHG/u1PvMv6Ng==",
      created: "neKG6qyyNI/4XyiK8dOUGXodNzQwbvxiHjF0xwz2TFI=",
      transaction_fee_configurations: [
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "YWinTOv4p75O3x0gwTs/5A==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "rWCOwpu2jWPfEn8TyZQsKw==",
          fee_description: null,
          fee_value: "7zwb8FmK8AAlE+LVwdebJA==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "CHgVDgpdSLQMF2e92C8jtA==",
          fee_description: null,
          fee_value: "YWinTOv4p75O3x0gwTs/5A==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "igG5/RWqdecrZAyvpZ2MtbDNcEAsloOA9k4WIb+FCn0=",
          fee_description: null,
          fee_value: "mIhXkzXjLpwgjS5mJGDyrA==",
          fee_type: "9qCmpR9tL9OuOyMCepL4QQ==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "8PrBa9vsAF2+uCx/5f13Jg==",
          fee_name: "6bg/NG/QhfTMhjbXdNAVyg==",
          fee_description: null,
          fee_value: "TmN904SMldiFtcHgpXve9A==",
          fee_type: "vScdnIitO0dwckA9Kn7gsA==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
        {
          order_type: "4O+C83wiJcv7YFwnXE7ssQ==",
          fee_name: "6bg/NG/QhfTMhjbXdNAVyg==",
          fee_description: null,
          fee_value: "TmN904SMldiFtcHgpXve9A==",
          fee_type: "vScdnIitO0dwckA9Kn7gsA==",
          fee_structure_type: "TmnYdeWil/aWyb1rlXRRAQ==",
        },
      ],
    },
  ],
  message: "Latest Security Prices",
});

console.log(value);
console.log(encrypt(value));
